export const VALID_PROFESSIONAL_DOCUMENT_STATUSES = [
  'PENDING',
  'APPROVED',
  'REJECTED',
  'NEW',
] as const;
export const VALID_PROFESSIONAL_DOCUMENT_TYPES = ['DEGREE', 'CERTIFICATE', 'OTHER'] as const;
export const VALID_IDENTITY_VERIFICATION_STATUSES = ['PENDING', 'APPROVED', 'REJECTED'] as const;
export const VALID_VERIFICATION_STATUSES = ['PENDING', 'APPROVED', 'REJECTED'] as const;
