export const themes = {
  light: {
    // ===== Surfaces =====
    background: '#F8F6F6',
    backgroundMuted: '#F1F5F9',
    surface: '#FFFFFF',
    backgroundCard: '#FFFFFF',

    // ===== Text =====
    appText: '#111827',
    colorMuted: '#6B7280',
    foreground: '#000',

    // ===== Field / Input =====
    fieldBackground: '#F1F5F9',

    // ===== Borders =====
    borderColor: '#D1D5DB',
    borderSubtle: '#E5E7EB',
    borderCard: '#252f41',
    cardBorder: '#DCDCE5',

    // ===== Brand =====
    primary: '$appPrimary',
    primaryHover: '$appPrimaryHover',
    primaryActive: '$appPrimaryHover',
    secondary: '#DDE6EE',
    secondaryHover: '#DDE6EE',

    // ===== Toast =====
    toastSuccessBg: '#dcfce7',
    toastSuccessBorder: '#15803d',
    toastSuccessText: '#14532d',

    toastErrorBg: '#fee2e2',
    toastErrorBorder: '#b91c1c',
    toastErrorText: '#7f1d1d',

    toastInfoBg: '#e0f2fe',
    toastInfoBorder: '#0369a1',
    toastInfoText: '#0c4a6e',

    // ===== Card =====
    statusSuccessBg: '#dcfce7',
    statusSuccessBorder: '#15803D',
    statusErrorBg: '#fee2e2',
    statusErrorBorder: '#f87171',
    statusInfoBg: '#E0F2FE',
    statusInfoBorder: '#0284C7',
    // ===== Table ======
    headerBackground: '#f8fafc',
    selectedBackground: '#e2e8f0',

    // ===== Item =======
    itemBackground: '#f1f5f9',

    // ===== Button ======
    tertiary: '#dde6ee',
    tertiaryHover: '#d2d5d8',

    // ===== Web Header =====
    webHeaderBgStart: '#f8fbff',
    webHeaderBgEnd: '#eef4ff',
    webHeaderBorder: 'rgba(29, 36, 51, 0.08)',
    webHeaderLogoText: '#1d2433',
    webHeaderNavText: '#56709c',
    webHeaderNavHover: '#1d66f2',
    webHeaderToggleBorder: 'rgba(29, 36, 51, 0.12)',
    webHeaderToggleBg: '#ffffff',
    webHeaderToggleText: '#2b3447',
    webHeaderToggleHover: '#f3f7ff',
    webHeaderLocaleActiveBg: '#1d66f2',
    webHeaderLocaleActiveText: '#ffffff',
    myLessonsPageBackground: '#F3F5F9',
    myLessonsTopNavBackground: '#FFFFFF',
    myLessonsTopNavBorder: '#E2E7F0',
    myLessonsBrandText: '#1D2433',
    myLessonsBrandPrimary: '#206BFF',
    myLessonsBrandBorder: 'rgba(28, 89, 207, 0.25)',
    myLessonsNavActive: '#2F7CFF',
    myLessonsNavInactive: '#6E7B94',
    myLessonsNavHover: '#1D66F2',
    myLessonsAvatarBackground: '#FFD7C7',
    myLessonsAvatarBorder: '#E7D3C7',
    myLessonsAvatarText: '#2A2D41',
    myLessonsHeaderTitle: '#1D2433',
    myLessonsHeaderDivider: '#E2E7F0',
    myLessonsPrimaryButton: '#1D66F2',
    myLessonsPrimaryButtonBorder: '#1D66F2',
    myLessonsPrimaryButtonHover: '#2F7CFF',
    myLessonsPrimaryButtonText: '#F6FAFF',
    myLessonsPromoTitle: '#1D2433',
    myLessonsPromoDescription: '#74829B',
    myLessonsPromoButtonBg: '#1D66F2',
    myLessonsPromoButtonBorder: '#1D66F2',
    myLessonsPromoButtonHover: '#2F7CFF',
    myLessonsPromoButtonText: '#F6FAFF',
    myLessonsPromoVisualBg: '#C7D6D4',
    myLessonsPromoVisualOverlay: 'rgba(255, 255, 255, 0.08)',
    myLessonsPromoVisualStickOne: '#CCAA7A',
    myLessonsPromoVisualStickTwo: '#C59762',
    myLessonsCardBorder: '#DCE5F2',
    myLessonsCardBackground: '#FFFFFF',
    myLessonsCalendarTitle: '#1D2433',
    myLessonsMonthNav: '#7F93BD',
    myLessonsSwitcherBackground: '#EDF2FA',
    myLessonsSwitcherBorder: '#DCE5F2',
    myLessonsSwitcherActiveBackground: '#D5E2F7',
    myLessonsSwitcherActiveText: '#1D2433',
    myLessonsSwitcherInactiveText: '#7688AB',
    myLessonsLegendText: '#788CA8',
    myLessonsFooterText: '#7E93BE',
    myLessonsGridHeaderBackground: '#F7FAFF',
    myLessonsGridBodyBackground: '#FFFFFF',
    myLessonsGridBorder: '#DCE5F2',
    myLessonsDayLabel: '#8FA1C4',
    myLessonsActiveDate: '#2F7CFF',
    myLessonsInactiveDate: '#1D2433',
    myLessonsActiveDayColumn: 'rgba(47, 124, 255, 0.1)',
    myLessonsCurrentColumn: 'rgba(47, 124, 255, 0.08)',
    myLessonsCurrentColumnGap: 'rgba(47, 124, 255, 0.06)',
    myLessonsGapCellBackground: '#F6F9FF',
    myLessonsTimeLabel: '#7F93BD',
    myLessonsNowLine: '#2F7CFF',
    myLessonsGapLabel: '#7389B5',
    myLessonsGapHint: '#5A709C',
    myLessonsEventBorder: 'rgba(0, 0, 0, 0.05)',
    myLessonsEventTutor: '#F4F7FF',
    myLessonsEventTime: '#C4D2F5',
    myLessonsCategoryEnglishBackground: 'rgba(47, 124, 255, 0.2)',
    myLessonsCategoryEnglishLabel: '#1D66F2',
    myLessonsCategoryEnglishDot: '#2F7CFF',
    myLessonsLessonsSectionTitle: '#1D2433',
    myLessonsLessonsCardBackground: '#FFFFFF',
    myLessonsLessonsCardBorder: '#E4E8F0',
    myLessonsLessonsPrimaryText: '#1D2433',
    myLessonsLessonsSecondaryText: '#7D8799',
    myLessonsLessonsMutedText: '#A1ADBE',
    myLessonsLessonsActionSecondaryBg: '#FFFFFF',
    myLessonsLessonsActionSecondaryBorder: '#D6DEEB',
    myLessonsLessonsActionSecondaryText: '#2B3447',
    myLessonsLessonsActionPrimaryBg: '#1D66F2',
    myLessonsLessonsActionPrimaryBorder: '#1D66F2',
    myLessonsLessonsActionPrimaryText: '#F6FAFF',
    myLessonsLessonsRatingBackground: '#F2F7FF',
    myLessonsLessonsRatingBorder: '#D9E5FF',
    myLessonsLessonsRatingText: '#2F7CFF',
    myLessonsLessonsEmptyBackground: '#F2F5F9',
    myLessonsLessonsEmptyBorder: '#E4E8F0',
    myLessonsLessonsEmptyIcon: '#C4CEDD',
    myLessonsLessonsEmptyTitle: '#1D2433',
    myLessonsLessonsEmptyDescription: '#8A95A8',
    myLessonsLessonsEmptyButtonBg: '#0F1F3D',
    myLessonsLessonsEmptyButtonBorder: '#0F1F3D',
    myLessonsLessonsEmptyButtonText: '#F6FAFF',

    statusWarningBg: '#FEF3C7',
    statusWarningBorder: '#D97706',

    priceCardBg: '#f0f9ff',
    priceCardBorder: '#e0f2fe',

    skeletonBg: '#Cbd5e1',

    // ===== Tutors =====
    tutorsPageBackground: '#F3F5F9',
    tutorsVideoOverlayBg: 'rgba(7, 15, 31, 0.72)',
    tutorsVideoFrameBg: '#0B1220',
    tutorsVideoPlayIcon: '#FFFFFF',
  },

  dark: {
    // ===== Surfaces =====
    background: '#101622',
    backgroundMuted: '#0B1220',
    surface: '#0F172A',
    backgroundCard: '#171f2f',

    // ===== Text =====
    appText: '#FFFFFF',
    colorMuted: '#9CA3AF',
    foreground: '#fff',

    // ===== Field / Input =====
    fieldBackground: '#334155',

    // ===== Borders =====
    borderColor: '#1F2937',
    borderSubtle: '#1F2937',
    borderCard: '#252f41',
    cardBorder: '#252f41',

    // ===== Brand =====
    primary: '#1253D5',
    primaryHover: '#104BC4',
    primaryActive: '#104BC4',
    secondary: '#1253D5',
    secondaryHover: '#2A344A',

    // ===== Toast =====
    toastSuccessBg: '#0F2E1C',
    toastSuccessBorder: '#15803d',
    toastSuccessText: '#bbf7d0',

    toastErrorBg: '#2A0F12',
    toastErrorBorder: '#b91c1c',
    toastErrorText: '#fecaca',

    toastInfoBg: '#0B2533',
    toastInfoBorder: '#0369a1',
    toastInfoText: '#bae6fd',

    // ===== Status Card =====
    statusSuccessBg: '#1F3D3B',
    statusSuccessBorder: '#6EE7B7',
    statusErrorBg: '#3F1E29',
    statusErrorBorder: '#FCA5A5',
    statusInfoBg: '#082F49',
    statusInfoBorder: '#38BDF8',
    // ===== Table ======
    headerBackground: '#1e293b',
    selectedBackground: '#172137',

    // ===== Item =======
    itemBackground: '#152a56',

    // ===== Button ======
    tertiary: '#1e293b',
    tertiaryHover: '#334155',

    // ===== Web Header =====
    webHeaderBgStart: '#0b1628',
    webHeaderBgEnd: '#101f3f',
    webHeaderBorder: 'rgba(255, 255, 255, 0.1)',
    webHeaderLogoText: '#ffffff',
    webHeaderNavText: '#cbd5e1',
    webHeaderNavHover: '#ffffff',
    webHeaderToggleBorder: 'rgba(255, 255, 255, 0.22)',
    webHeaderToggleBg: 'rgba(255, 255, 255, 0.04)',
    webHeaderToggleText: '#e7eeff',
    webHeaderToggleHover: 'rgba(255, 255, 255, 0.12)',
    webHeaderLocaleActiveBg: 'rgba(29, 102, 242, 0.75)',
    webHeaderLocaleActiveText: '#ffffff',
    myLessonsPageBackground: '#050D1A',
    myLessonsTopNavBackground: '#070F1F',
    myLessonsTopNavBorder: 'rgba(20, 44, 89, 0.9)',
    myLessonsBrandText: '#F2F6FF',
    myLessonsBrandPrimary: '#206BFF',
    myLessonsBrandBorder: 'rgba(255, 255, 255, 0.25)',
    myLessonsNavActive: '#2F7CFF',
    myLessonsNavInactive: '#A6B9DD',
    myLessonsNavHover: '#E8EEFE',
    myLessonsAvatarBackground: '#FFD7C7',
    myLessonsAvatarBorder: 'rgba(255, 255, 255, 0.2)',
    myLessonsAvatarText: '#2A2D41',
    myLessonsHeaderTitle: '#F2F6FF',
    myLessonsHeaderDivider: 'rgba(20, 44, 89, 0.9)',
    myLessonsPrimaryButton: '#1D66F2',
    myLessonsPrimaryButtonBorder: '#1D66F2',
    myLessonsPrimaryButtonHover: '#2F7CFF',
    myLessonsPrimaryButtonText: '#F6FAFF',
    myLessonsPromoTitle: '#DDE7FF',
    myLessonsPromoDescription: '#7787A8',
    myLessonsPromoButtonBg: '#182A4D',
    myLessonsPromoButtonBorder: '#182A4D',
    myLessonsPromoButtonHover: '#203861',
    myLessonsPromoButtonText: '#E7EEFF',
    myLessonsPromoVisualBg: '#74918A',
    myLessonsPromoVisualOverlay: 'rgba(12, 19, 31, 0.15)',
    myLessonsPromoVisualStickOne: '#CCAA7A',
    myLessonsPromoVisualStickTwo: '#C59762',
    myLessonsCardBorder: 'rgba(20, 44, 89, 0.9)',
    myLessonsCardBackground: '#08142D',
    myLessonsCalendarTitle: '#EDF3FF',
    myLessonsMonthNav: '#7F93BD',
    myLessonsSwitcherBackground: '#13233F',
    myLessonsSwitcherBorder: 'rgba(255, 255, 255, 0.06)',
    myLessonsSwitcherActiveBackground: '#40577F',
    myLessonsSwitcherActiveText: '#F6FAFF',
    myLessonsSwitcherInactiveText: '#8EA4CE',
    myLessonsLegendText: '#8DA3CD',
    myLessonsFooterText: '#7E93BE',
    myLessonsGridHeaderBackground: '#0A142D',
    myLessonsGridBodyBackground: '#091327',
    myLessonsGridBorder: 'rgba(20, 44, 89, 0.9)',
    myLessonsDayLabel: '#96A7CC',
    myLessonsActiveDate: '#2F7CFF',
    myLessonsInactiveDate: '#E8EEFE',
    myLessonsActiveDayColumn: 'rgba(18, 43, 90, 0.7)',
    myLessonsCurrentColumn: 'rgba(16, 42, 94, 0.45)',
    myLessonsCurrentColumnGap: 'rgba(16, 42, 94, 0.3)',
    myLessonsGapCellBackground: 'rgba(9, 19, 39, 0.75)',
    myLessonsTimeLabel: '#7F93BD',
    myLessonsNowLine: '#2F7CFF',
    myLessonsGapLabel: '#7389B5',
    myLessonsGapHint: '#5A709C',
    myLessonsEventBorder: 'rgba(255, 255, 255, 0.08)',
    myLessonsEventTutor: '#DDE6FD',
    myLessonsEventTime: '#9FB2DC',
    myLessonsCategoryEnglishBackground: 'rgba(18, 63, 152, 0.7)',
    myLessonsCategoryEnglishLabel: '#66A9FF',
    myLessonsCategoryEnglishDot: '#2F7CFF',
    myLessonsLessonsSectionTitle: '#EEF4FF',
    myLessonsLessonsCardBackground: '#08142D',
    myLessonsLessonsCardBorder: 'rgba(20, 44, 89, 0.9)',
    myLessonsLessonsPrimaryText: '#F0F5FF',
    myLessonsLessonsSecondaryText: '#9BB0D8',
    myLessonsLessonsMutedText: '#7E93BE',
    myLessonsLessonsActionSecondaryBg: '#08142D',
    myLessonsLessonsActionSecondaryBorder: 'rgba(20, 44, 89, 0.9)',
    myLessonsLessonsActionSecondaryText: '#D9E5FF',
    myLessonsLessonsActionPrimaryBg: '#1D66F2',
    myLessonsLessonsActionPrimaryBorder: '#1D66F2',
    myLessonsLessonsActionPrimaryText: '#F6FAFF',
    myLessonsLessonsRatingBackground: 'rgba(47, 124, 255, 0.18)',
    myLessonsLessonsRatingBorder: 'rgba(47, 124, 255, 0.4)',
    myLessonsLessonsRatingText: '#70A8FF',
    myLessonsLessonsEmptyBackground: '#0F1B34',
    myLessonsLessonsEmptyBorder: 'rgba(20, 44, 89, 0.9)',
    myLessonsLessonsEmptyIcon: '#6E82AA',
    myLessonsLessonsEmptyTitle: '#EEF4FF',
    myLessonsLessonsEmptyDescription: '#8DA3CD',
    myLessonsLessonsEmptyButtonBg: '#182A4D',
    myLessonsLessonsEmptyButtonBorder: '#182A4D',
    myLessonsLessonsEmptyButtonText: '#E7EEFF',

    statusWarningBg: '#422006',
    statusWarningBorder: '#F59E0B',

    priceCardBg: '#1e293b',
    priceCardBorder: '#102645',

    skeletonBg: '#1F2937',

    // ===== Tutors =====
    tutorsPageBackground: '#050D1A',
    tutorsVideoOverlayBg: 'rgba(0, 0, 0, 0.75)',
    tutorsVideoFrameBg: '#000000',
    tutorsVideoPlayIcon: '#FFFFFF',
  },
};
